Add CarbonateProducer component
landlab/landlab pull request #1284
Opened 2021-03-18 23:29 UTC by mcflugen

This pull request adds a new component, *CarbonateProducer*, that grows carbonate reefs in the ocean. It's not done yet but will be soon.

2021-03-19 17:35 UTC, gregtucker requested changes
Looks great! Just a few things to tidy up. Happy to pitch in and take care of some/all of them, just ping me. (This is fun for me, as Bob A and I have for several years used this same function for a 1D carbonate modeling class exercise in GEOL 5775! Would be neat to share this 2+D component with the class next time we offer it, likely spring 2022)

2021-03-19 17:35 UTC, gregtucker commented on landlab/components/carbonate/carbonate_producer.py
> +def smooth_heaviside(x, width=0.5, out=None):
Add docstring for `smooth_heaviside()`? Also, if this fn is likely to be useful for other components, consider moving to utils.

2021-03-19 17:35 UTC, gregtucker commented on landlab/components/carbonate/carbonate_producer.py
> +    """When I properly understand how to write the code, I'll write this intro ;-)"""
Docstring needed

2021-03-19 17:35 UTC, gregtucker commented on landlab/components/carbonate/carbonate_producer.py
> +    _name = "The Producer of Carbonate"
To be consistent with other components, suggest using the same name as the class (CarbonateProducer)

2021-03-19 17:35 UTC, gregtucker commented on landlab/components/carbonate/carbonate_producer.py
> +        grid: ModelGrid (RasterModelGrid, HexModelGrid, etc.)
Descriptions of other params needed

2021-03-19 17:35 UTC, gregtucker commented on landlab/components/carbonate/carbonate_producer.py
> +        self.extinction_coefficient = extinction_coefficient
Shouldn't these be private variables, since they have public getters and setters defined below?

2021-03-19 17:35 UTC, gregtucker commented on landlab/components/carbonate/carbonate_producer.py
> +            also needs, but not yet defined/coded
I think this text block can be removed

2021-03-19 17:35 UTC, gregtucker commented on landlab/components/carbonate/carbonate_producer.py
> +    def calc_production_with_depth(self, water_depth, out=None):
Great to include `out=` for economy of memory, we should make this a semi-standard practice in components!

2021-03-19 17:35 UTC, gregtucker commented on landlab/components/carbonate/carbonate_producer.py
> +    def calc_carbonate_production_at_node(self, out=None):
To be a depth/thickness, I think this needs to be multiplied by time-step size

2022-02-11 02:49 UTC, gregtucker approved these changes

2022-02-25 19:02 UTC, gregtucker commented
@mcflugen do you have time to take a look at the added tests and tutorial?

2022-02-25 19:20 UTC, mcflugen commented
@gregtucker I'll have a look at it this afternoon.

2022-02-26 15:45 UTC, merged