Updating KinwaveImplicitOverlandFlow to accept distributed runoff and/or roughness
landlab/landlab pull request #2098
Opened 2024-12-30 21:48 UTC by amanaster2

### Description

Updated `KinwaveImplicitOverlandFlow` to accept fields (i.e., arrays of floats) for both `runoff_rate` and `roughness`. Wanted to enhance the functionality for future use. Instead of accepting a normal (but really, what is normal?) array, I've made it such that the user must define the field on the ModelGrid where the values are stored.

### Checklist - did you ...

- [ - ] Add a [news fragment](https://landlab.readthedocs.io/en/master/development/contribution/index.html#news-entries) file entry if necessary? _(Is this necessary?)_
- [ x ] Add / update tests if necessary?
- [ x ] Add new / update outdated documentation? _(Assuming you mean the docstring.)_
- [ x ] All tests have passed? _(I ran `nox -s test` at the top level, and everything passed. Let me know if I'm supposed to run something else, though.)_
- [ x ] Formatted code with black?
- [ x ] Removed lint reported by flake8?
- [ - ] Successful documentation built? (if documentation added or modified) _(This is repeatedly failing on my computer with an error about the module 'importlib_resources' not existing... I'm confused.)_

2025-01-03 17:35 UTC, mcflugen requested changes
@amanaster2 Thanks for this contribution! I've added a few comments for you to address, but nothing major.

2025-01-03 17:35 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +            self._runoff_rate = runoff_rate / 3.6e6
We have a function that does this. The following is more compact and, I think, still does what you want,
```python
self._roughness = self._grid.return_array_or_field_values(roughness, at="node")
```

2025-01-03 17:35 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +        self._vel_coef = 1.0 / self._roughness  # do division now to save time
Because you calculate this in `__init__`, any changes to the roughness field will not be seen in future calculations. I think it would be better if this were moved into the `run_one_step` method. If you do that, there's probably no need to save this temporary calculation as a separate variable—just use the roughness directly.

2025-01-03 17:35 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +        if isinstance(new_rate, str):
As with a previous comment, you can use the `return_array_or_field_values` method.

2025-01-03 17:35 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +            assert new_rate > 0
Remove the `assert` statement, it should only be used for debugging. If you want an error to be raised, maybe something like the following,
```python
if new_rate <= 0.0:
    raise ValueError(f"runoff_rate must be positive ({new_rate})")
```

2025-01-03 17:35 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +                )
To avoid repeated code and, I think, make this a little clearer, how about,
```python
if np.isscalar(self._roughness):
    roughness_at_core_nodes = self._roughness
else:
    roughness_at_core_nodes = self._roughness[cores]

self._alpha[cores] = (
    self._grad_width_sum[cores]
    * dt
    / (self._grid.area_of_cell[self._grid.cell_at_node[cores]])
    / roughness_at_core_nodes
)
```

2025-01-03 17:35 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +                    )
Same as above with the roughness, use `np.isscalar`.

2025-01-03 17:35 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +                    )  # this is manning/chezy/darcy
Check if roughness is a scalar using `np.isscalar`.

2025-01-03 17:35 UTC, mcflugen commented on tests/components/overland_flow/test_kinwave_implicit.py
> +    mg2.add_field("r2", r2, at="node")
Use,
```python
mg2.add_ones("r2", at="node")
```

2025-01-03 17:35 UTC, mcflugen commented on tests/components/overland_flow/test_kinwave_implicit.py
> +    mg2.add_field("r2", r2, at="node")
Use,
```python
mg2.add_full("r2", 0.03, at="node")
```

2025-01-03 17:35 UTC, mcflugen commented on tests/components/overland_flow/test_kinwave_implicit.py
> +        mg2, runoff_rate=1.0, roughness=r2, depth_exp=5 / 3
I think you want `roughness="r2"` to check that roughness can be passed as the name of an *at-node* field.

2025-01-03 17:35 UTC, mcflugen commented on tests/components/overland_flow/test_kinwave_implicit.py
> +    test_kinwave_roughness_field()
None of this is necessary, I suggest removing these lines.

2025-01-03 17:43 UTC, mcflugen commented
> Add a [news fragment](https://landlab.readthedocs.io/en/master/development/contribution/index.html#news-entries) file entry if necessary? (Is this necessary?)

Yes, this is necessary, it will go into our release notes. Just one sentence that describes what you've added is fine.

> Successful documentation built? (if documentation added or modified) (This is repeatedly failing on my computer with an error about the module 'importlib_resources' not existing... I'm confused.)

The docs seem to be building fine, so you don't need to worry about this. There is a version of the docs [for this pull request](https://landlab--2098.org.readthedocs.build/en/2098/generated/api/landlab.components.overland_flow.generate_overland_flow_implicit_kinwave.html) you can have a look at to see that things look as you want them to.

2025-01-03 17:49 UTC, amanaster2 commented on tests/components/overland_flow/test_kinwave_implicit.py
> +        mg2, runoff_rate=1.0, roughness=r2, depth_exp=5 / 3
Oops, definitely want `roughness="r2"`! Thanks for catching that.

2025-01-03 17:49 UTC, amanaster2 commented on tests/components/overland_flow/test_kinwave_implicit.py
> +    test_kinwave_roughness_field()
Just to confirm: the whole block?

2025-01-03 17:54 UTC, amanaster2 commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +            self._runoff_rate = runoff_rate / 3.6e6
So it would also work for `self._runoff_rate  = self._grid.return_array_or_field_values(runoff_rate, at="node")`?

2025-01-03 17:55 UTC, amanaster2 commented
Thanks, @mcflugen !! I'll get these changes incorporated and add a news fragment file entry.

2025-01-03 17:59 UTC, amanaster2 commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +            stored on the ModelGrid.
Units are on the next line; should I move them up?

2025-01-03 18:04 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +            stored on the ModelGrid.
Oops, I missed that. Sorry. You may as well move them up just to keep the line lengths consistent.

2025-01-03 18:05 UTC, amanaster2 commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +        if isinstance(new_rate, str):
Oops, this addresses my above question. Nevermind!

2025-01-03 18:05 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +            stored on the ModelGrid.
While you're at it, I think you can remove the sentence that begins with, "The value provided...".

2025-01-03 18:08 UTC, mcflugen commented on tests/components/overland_flow/test_kinwave_implicit.py
> +    test_kinwave_roughness_field()
Yeah, the whole block.

2025-01-03 18:11 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +            self._runoff_rate = runoff_rate / 3.6e6
Yes, that should also work.

As with the velocity coefficient, because you divide the runoff rate by 3.6e6 here, it creates a copy of the array and any changes to the field will not be reflected in future calculations. It probably makes sense to move some of this into `run_one_step`.

2025-01-03 18:44 UTC, amanaster2 commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +            self._runoff_rate = runoff_rate / 3.6e6
Since there's only one place in the `run_one_step` method where the runoff rate is used, I just moved the division by 3.6e6 to that location.

2025-01-03 18:49 UTC, amanaster2 commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +        self._vel_coef = 1.0 / self._roughness  # do division now to save time
Changed such that only roughness is used, and created a getter and setter for roughness so the value(s) can be updated easily.

2025-01-03 20:34 UTC, amanaster2 commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +            self._runoff_rate = runoff_rate / 3.6e6
Note: `self._grid.return_array_or_field_values()` works only if the value provided _isn't_ a single float. Since I want to be able to use a single float or an array/field, I think I'm going to keep the code similar to what I had previously:
```python
if isinstance(roughness, float):
    self._roughness = roughness
else:
    self._roughness = self._grid.return_array_or_field_values(
        roughness, at="node"
    )

if isinstance(runoff_rate, float):
    self._runoff_rate = runoff_rate
else:
    self._runoff_rate = self._grid.return_array_or_field_values(
        runoff_rate, at="node"
    )
```

2025-01-03 20:38 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +            self._runoff_rate = runoff_rate / 3.6e6
Ok. I think `return_array_or_field_values` should probably work with a scalar value but I'll make that change in a different pull request and then update this code later.

2025-01-03 20:48 UTC, amanaster2 commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +            self._runoff_rate = runoff_rate / 3.6e6
Oh cool. Does that mean we wouldn't have to do any `np.isscalar` checks further down in the code? Since `return_array_or_field_values` would return an array?

2025-01-03 22:39 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +            self._runoff_rate = runoff_rate / 3.6e6
Yes, I think that would be the case but I haven't thought it through. There might be some reason we would want to keep a scalar, a scalar.

2025-01-03 22:39 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +        if np.isinstance(new_rate, float):
Just `isinstance`, not `np.isinstance`.

2025-01-03 22:57 UTC, amanaster2 commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +        if np.isinstance(new_rate, float):
Lol, I also fixed it before I saw that you fixed it :-D

2025-01-04 02:41 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +        runoff_rate : array_like of float or str (defaults to 1 mm/hr)
For both `runoff_rate` and `roughness`, how about:
```
runoff_rate : str or array_like of float
```
This makes it clear that it's not an array of either floats or strings but, rather, a string or an array of floats.

2025-01-04 02:43 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
>          depth_exp : float (defaults to 1.5)
For all of these keyword parameters, it's not needed to include the default values since they are given in the function signature.

2025-01-04 04:01 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +            raise ValueError(f"roughness must be positive ({new_rough})")
If `new_rough` is a `str`, this check will fail.

2025-01-04 04:07 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +    def roughness(self, new_rough):
I'm not sure if `new_rough` should be able to be a field name here. What do you think?

Are there cases where someone would want to change the field that contains the roughness?

What should happen if this component was created with a roughness specified as a field name and then a user subsequently uses this setter with a roughness that's an array? Should the field that was specified when the component was instantiated be updated?

2025-01-04 06:22 UTC, amanaster2 commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +    def roughness(self, new_rough):
Hmmm. This is a good question.

When I wrote this, I was thinking about a very specific case: a roadside ditch line that goes from a "bare" state (i.e., loose soil) to an "eroded" state (i.e., armored bed)---the roughness approximately doubles. This would probably happen over the course of a couple of storms, so if I used a single kinwave instantiation over the course of those storms, I'd probably want to update the roughness... But, like I said, this is a super specific case... So we could probably get rid of this setter, if it makes more sense to do so.

If we keep the setter: 
If the component is instantiated with a roughness field then is subsequently updated with an array, we would probably want to update the initial field, no? If the person wanted to maintain the initial values, they could create a copy. 

Let me think about this a bit more. I'll come back to this next week, but let me know if you have any thoughts in the meantime. 😄

2025-01-04 06:22 UTC, amanaster2 commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +            raise ValueError(f"roughness must be positive ({new_rough})")
Same with the check for `new_rate` above... Hrm. I'll come back to this when it's not after 11pm on a Friday 😴

2025-01-06 17:57 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +    def roughness(self, new_rough):
I think the setter is a fine idea. My comment was about the specific case of the setter accepting a string, rather than an array-like object. Is there ever a case where you would want to change the field that the component is tracking for roughness values? That is, something like,
```python
overland_flow = KinwaveImplicitOverlandFlow(grid, roughness="roughness")
overland_flow.roughness = "roughness_new"
```
I'm not sure this is something we would want to support.

How about the following: if the component is instantiated using a string for the roughness, that tells the component to track that field for roughness values and if you want to update those values, you ***must to do that through the field***?

So maybe the setter would look something like,
```python
@roughness.setter
def roughness(self, new_rough):
    if isinstance(self._roughness, str):
        raise ValueError(
            "unable to set roughness. KinwaveImplicitOverlandFlow is currently tracking a node field"
            f" named {self._roughness} for roughness values"
        )
    if np.any(new_rough < 0.0):
        raise ValueError("roughness must be positive")
    self._roughness = np.asarray(new_rough)
```

2025-01-06 18:18 UTC, amanaster2 commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +    def roughness(self, new_rough):
OH, I see what you mean! Sorry, I misunderstood originally. Thank you for the clarification. 

Yes, I agree with this! Accepting a string in the setter would complicate things unnecessarily. 
I can make these updates today!

2025-01-07 00:02 UTC, amanaster2 commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +    def roughness(self, new_rough):
So, I realized that I made everything much more complicated than necessary by allowing `roughness` and `runoff_rate` to be fields. This was made apparent as I was trying to fix the setter (`self._roughness` never yielded a `str` with how I had coded the rest). After fumbling around for a while, I decided to streamline the code such that those keywords accept only array_like objects (and updated the docstrings and news fragment as necessary). I'm running `nox -s test` on the updates now to ensure everything is working, then I'll push my commits.

2025-01-07 02:22 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +    def roughness(self, new_rough):
Are you sure? It seemed like a good idea to me! I do like simpler and streamlined, though.

2025-01-07 03:26 UTC, amanaster2 commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +    def roughness(self, new_rough):
I think so, yes! At least for now. We could merge this PR now (assuming it's all good), and include the fields in a future update of the component? (Should I open an issue and reference this PR as a reminder?) I'm going to be deep in Landlab land for at least the next 6 months, so I can definitely come back to it 😸

2025-01-07 03:44 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +    def roughness(self, new_rough):
Sure, that sounds good. It's probably better as two separate pull requests, anyway.

2025-01-07 04:07 UTC, mcflugen requested changes
A few more comments.

2025-01-07 04:07 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +        self._roughness = roughness
If either of these are arrays, a reference to the array is being saved. Is that what you want or should a copy be made? i.e.
```python
self._runoff_rate = np.array(runoff_rate)
```
If a reference is saved, then if the passed array is changed outside of the component, the component's value will also be updated. Using a reference would save memory and the time taken to make a copy but could, potentially lead to unexpected behavior.

2025-01-07 04:07 UTC, mcflugen commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +        self._roughness = roughness
The same applies lower down for the getters and setters.

2025-01-07 17:41 UTC, amanaster2 commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +        self._roughness = roughness
Good point! I've made this change. 

Since all values for `runoff_rate` and `roughness` will now be arrays, I've also updated the code in `run_one_step` to check for a single float using `np.ndim() == 0` rather than `np.isscalar()`.

2025-01-10 01:43 UTC, amanaster2 commented on src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
> +        """Runoff rate at nodes."""
I liked the idea of returning a read-only view of the arrays, so I did that! Committed and pushed, tests running now!

2025-01-30 00:37 UTC, amanaster2 commented
Side note: I merged `master` into my branch, so the checks ran again, and it looks like there was 1 that errored and 1 that skipped. I didn't make any changes to my code.

2025-02-11 22:05 UTC, amanaster2 commented
Hey @mcflugen ! Are there other changes I need to make to the component, or is it good to merge? (Once the checks finish; I just updated the branch to be in sync with `master`, so the checks are running again.) One of my colleagues was asking about using this updated version of the component, so I figured I'd give this a bump!

2025-02-13 18:25 UTC, mcflugen commented
@amanaster2 I think this is good to go but let me have another quick look.

2025-02-26 22:51 UTC, mcflugen commented
@amanaster2 Sorry, I added some tests to your branch that cover the code you modified and was waiting for you to have a look to see if they're ok. I see now, though, that I never actually asked to to have a look. So sorry! If they look good to you, this is ready to go.

2025-02-27 20:11 UTC, amanaster2 commented
@mcflugen No worries!! I just looked through all of it, and it looks good to me!

2025-02-27 20:13 UTC, merged